// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gouddckfvbjntqburbyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdvdWRkY2tmdmJqbnRxYnVyYnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQzNjQwNzIsImV4cCI6MjA4OTk0MDA3Mn0.bhMH5BLDk7FSfo6DqDP8WCEwtWGVPBvm5SvQUZgbPmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});